### ISSUE TITLE
got an error using CDN

### ISSUE THREAD

**Issue by CarlosBCIII** [chartist-js/chartist#1314]
Uncaught TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at Object.c.createSvg (chartist.js:330:42)
    at f.e [as createChart] (chartist.js:4190:25)
    at f.h (chartist.js:1925:10)

**Comment by Arantiryo** [comment]
Hi @CarlosBCIII 👋 

Is the issue still relevant for you with the latest version (`v1.1.2`)?
