### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'x' in null

### ISSUE THREAD

**Issue by waitingcheung** [chartist-js/chartist#995]
The [test case](https://github.com/gionkunz/chartist-js/blob/develop/test/spec/spec-core.js#L441) of ``splitIntoSegments`` missed the value of ``null``.

If using this array for ``makeValues``, it could not remove the ``null`` value and the following TypeError occurs.

```js
var values = makeValues([1,undefined,undefined,4,undefined,null]);
```

```
file:///path/chartist.js:678
    return typeof value === 'object' && ('x' in value || 'y' in value);
                                             ^

TypeError: Cannot use 'in' operator to search for 'x' in null
    at Object.Chartist.isMultiValue (file:///path/chartist.js:678:46)
    at Object.Chartist.getMultiValue (file:///path/chartist.js:691:17)
    at Object.Chartist.splitIntoSegments (file:///path/chartist.js:1140:19)
```

**Comment by Arantiryo** [comment]
Hello @waitingcheung 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the issue is still relevant to you so we can further look into it!
